language: android
sudo: false
script:
- jdk_switcher use oraclejdk8
- echo sdk.dir $ANDROID_HOME > local.properties
- export TERM=dumb
- export JAVA_OPTS="-XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError
  -Xmx2048m"
- "./gradlew assemble"
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
before_install:
- yes | sdkmanager "platforms;android-27"
deploy:
  provider: releases
  api_key:
    secure: IMjEwxUfJ2OBinnrxccIS9GW67fs9hjpqqlqt6xPsObV20Sey+PKXn4gPairKbv6yYzIcrJP7Or/5wcOLVxvO6EArUUV0NlfQ0MYP1x+Yckj2wdUq/YzoPFFFP/5F1oQmeDNaJP7XKvuZi7ALdMdByqe2owLJORs7dtv/fQ6qo8tqEjtTtzJKm2Ma1HzlrZWiwr2mz7FEPGr9SD+yBWTX2M7rPwxXJ0ugQKWDyxBR9y3kZtXC2w+it6sTjsc/KZl/KEhV/2AZpbNpYagacaitQFf+EQbGOkvNm26wNBOtO28NSii7dGjiaXkTv7zgmzu/8M8MP5wfiJzSl4Gq+feJS6QgCNg/mA6fkiNSTQy7Wa+pgYzEQeS1zoAUKctclIak6cmXbp9uJmF+7MZSRtmM3ViPrRAvPDyNQ53SvqWMUW8BjoKYJJq5IhlG64SYCieMj90wnsfDAdLpgVoBx8c+vlcFcUdpQnxYPWBhOg357b6mV5V6SoksMuajW7PvO33f+rQaLZxp/6b1RjqMIgPWQWDQiyLL4VDEc9vbAqpwesT8sT7zuZPIo7ovaPzCUJ99gsDjCoTLcjUJWgu1GUFHlZcks0Q1f026vYfvWhShwuh7NQRHKfPYUMK18LahGxEeEeV6fVPXJWVfnBMDURL5hnRnEEDku6UDxOMris7vBw=
  file: test
  on:
    repo: dasbaumwolltier/android_packages_apps_GmsCore
